name: Update Data
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  update_symbol_list:
    name: Update Traits periodically
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: |
          python data/traits.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data
          git commit -m "Updated Traits on `date` with GitHub Actions" || echo "No Changes to Commit"
          git push origin main || echo "No Changes to Commit"
